######################################################################
# Variables specific to OMERO read-only servers
# See omero-hosts.yml for common OMERO variables
######################################################################

###
### ROLE: ome.omero_server  
###   https://github.com/ome/ansible-role-omero-server/
###

omero_server_dbuser: omeroreadonly
omero_server_dbpassword: "{{ idr_secret_postgresql_password_ro | default('omero') }}"

idr_omero_web_user_dropdown: false

# Set this to 'ro' to mount /data/BioFormatsCache on read-only servers as
# read-only, default is 'rw'
# idr_bioformatscache_readwrite:
