---
# Initialise openstack volumes from inside VMs if necessary

- hosts: database-hosts
  roles:
  - role: ome.storage_volume_initialise
    storage_volume_initialise_device: "{{ database_db_vol_dev | default('/dev/vdb') }}"
    storage_volume_initialise_mount: /var/lib/pgsql

- hosts: omeroreadwrite-hosts
  roles:
  - role: ome.storage_volume_initialise
    storage_volume_initialise_device: "{{ omero_data_vol_dev | default('/dev/vdb') }}"
    storage_volume_initialise_mount: /data

- hosts: proxy-hosts
  roles:
  - role: ome.storage_volume_initialise
    storage_volume_initialise_device: "{{ gateway_nginxcache_vol_dev | default('/dev/vdb') }}"
    storage_volume_initialise_mount: /var/cache/nginx

# Use this group for any other IDR VMs that should have a volume mounted on /data
- hosts: data-hosts
  roles:
  - role: ome.storage_volume_initialise
    storage_volume_initialise_device: "{{ data_vol_dev | default('/dev/vdb') }}"
    storage_volume_initialise_mount: /data
