# Install OMERO.web on the IDR

# TODO: Add omeroweb hosts group
- hosts: idr-omero-hosts

  roles:
  - role: ome.redis
  - role: ome.omero_web

  # Vars are in group_vars/omero-hosts.yml

  environment: "{{ idr_ANSIBLE_ENVIRONMENT_VARIABLES | default({}) }}"
